name: Build

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pip install build twine
      - run: python -m build
      - run: twine check dist/*

      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/
