name: CI

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: tylerteichmann/ci/.github/workflows/ci-py.yaml@main
    with:
      python-version: "3.12"
      python-versions: '["3.12", "3.13", "3.14"]'
