name: Release

on:
  push:
    tags: ["v*"]

jobs:
  version-check:
    uses: tylerteichmann/ci/.github/workflows/version-check-py.yaml@main
    with:
      tag: ${{ github.ref_name }}

  ci:
    uses: tylerteichmann/ci/.github/workflows/ci-py.yaml@main
    with:
      python-version: "3.12"
      python-versions: '["3.12", "3.13", "3.14"]'

  publish-testpypi:
    needs: [version-check, ci]
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish-pypi:
    needs: publish-testpypi
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1

  release:
    needs: publish-pypi
    uses: tylerteichmann/ci/.github/workflows/release-py.yaml@main
    permissions:
      contents: write
