name: Release

on:
  release:
    types: [published]

jobs:
  checks:
    uses: tylerteichmann/ci/.github/workflows/release-py.yaml@main
    with:
      tag: ${{ github.event.release.tag_name }}
      python-version: "3.12"
      python-versions: '["3.12", "3.13", "3.14"]'

  publish-testpypi:
    needs: checks
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish-pypi:
    needs: publish-testpypi
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
